import type { Metadata } from "next";
import Link from "next/link";
import { CultureCard } from "@/components/cards";
import { Localized } from "@/components/localized";
import { CTASection, PageIntro, SectionHeading } from "@/components/ui";
import { cultureIdeas } from "@/content/resources";

export const metadata: Metadata = { title: "Language & Culture", description: "Explore how culture moves through everyday English, French, Spanish, humor, politeness, music, and social behavior.", alternates: { canonical: "/culture" } };

function Cards() { return <div className="culture-list">{cultureIdeas.map((item, index) => <CultureCard key={item.title} item={item} index={index} />)}</div>; }

export default function CulturePage() {
  const enTopics = ["Mexico", "France", "English-speaking cultures", "Cross-cultural communication", "Humor", "Politeness", "Everyday expressions", "Music", "Film", "Social behavior"];
  const esTopics = ["México", "Francia", "Culturas anglófonas", "Comunicación intercultural", "Humor", "Cortesía", "Expresiones cotidianas", "Música", "Cine", "Comportamiento social"];
  const frTopics = ["Mexique", "France", "Cultures anglophones", "Communication interculturelle", "Humour", "Politesse", "Expressions quotidiennes", "Musique", "Cinéma", "Comportement social"];
  return <Localized
    en={<><PageIntro eyebrow="Culture · Meaning in motion" title="Language is culture in motion." copy="Words carry habits, humor, distance, warmth, history, and ways of seeing. Learn what is happening around the sentence." accent="wine" note="Observe before translating" /><section className="section culture-feature"><div className="container culture-feature__grid"><div className="culture-feature__visual" aria-hidden="true"><span>AHORITA</span><i>now / soon / later</i><b>context decides</b></div><div><p className="eyebrow">Field note · Mexico</p><h2>The dictionary gives you a definition. Life gives you the meaning.</h2><p>Why can one word mean now, soon, in a little while, or perhaps not today? Because people communicate with situations as much as vocabulary.</p><Link href="/resources/what-ahorita-means-in-mexico">Read the field note <span aria-hidden="true">→</span></Link></div></div></section><section className="section"><div className="container"><SectionHeading eyebrow="Culture notes" title="Read between the words." intro="Short editorial explorations of the social worlds inside language." /><Cards /></div></section><section className="section topic-index"><div className="container"><p className="eyebrow">Future shelves</p><h2>A growing index of culture.</h2><div>{enTopics.map((topic) => <span key={topic}>{topic}</span>)}</div></div></section><CTASection eyebrow="Culture becomes personal" title="What world do you want to enter?" copy="Build a Language Map around the people, places, media, and cultural questions that already pull you in." /></>}
    es={<><PageIntro eyebrow="Cultura · El significado en movimiento" title="El idioma es cultura en movimiento." copy="Las palabras llevan hábitos, humor, distancia, cercanía, historia y maneras de ver el mundo. Aprende qué está ocurriendo alrededor de la frase." accent="wine" note="Observa antes de traducir" /><section className="section culture-feature"><div className="container culture-feature__grid"><div className="culture-feature__visual" aria-hidden="true"><span>AHORITA</span><i>ahora / pronto / después</i><b>el contexto decide</b></div><div><p className="eyebrow">Nota de campo · México</p><h2>El diccionario te da una definición. La vida te da el significado.</h2><p>¿Por qué una palabra puede significar ahora, pronto, dentro de un rato o quizá no hoy? Porque las personas se comunican con situaciones tanto como con vocabulario.</p><Link href="/resources/what-ahorita-means-in-mexico">Leer la nota de campo <span aria-hidden="true">→</span></Link></div></div></section><section className="section"><div className="container"><SectionHeading eyebrow="Notas culturales" title="Lee entre las palabras." intro="Exploraciones editoriales breves de los mundos sociales que viven dentro del idioma." /><Cards /></div></section><section className="section topic-index"><div className="container"><p className="eyebrow">Próximas colecciones</p><h2>Un índice cultural en crecimiento.</h2><div>{esTopics.map((topic) => <span key={topic}>{topic}</span>)}</div></div></section><CTASection eyebrow="La cultura se vuelve personal" title="¿A qué mundo quieres entrar?" copy="Construye un Mapa de Idioma alrededor de las personas, lugares, medios y preguntas culturales que ya despiertan tu curiosidad." /></>}
    fr={<><PageIntro eyebrow="Culture · Le sens en mouvement" title="La langue est la culture en mouvement." copy="Les mots transportent des habitudes, de l'humour, de la distance, de la chaleur, de l'histoire et des façons de voir. Apprenez ce qui se passe autour de la phrase." accent="wine" note="Observer avant de traduire" /><section className="section culture-feature"><div className="container culture-feature__grid"><div className="culture-feature__visual" aria-hidden="true"><span>AHORITA</span><i>maintenant / bientôt / plus tard</i><b>le contexte décide</b></div><div><p className="eyebrow">Note de terrain · Mexique</p><h2>Le dictionnaire vous donne une définition. La vie vous donne le sens.</h2><p>Pourquoi un seul mot peut-il signifier maintenant, bientôt, dans un moment, ou peut-être pas aujourd'hui ? Parce que les gens communiquent avec des situations autant qu'avec du vocabulaire.</p><Link href="/resources/what-ahorita-means-in-mexico">Lire la note de terrain <span aria-hidden="true">→</span></Link></div></div></section><section className="section"><div className="container"><SectionHeading eyebrow="Notes culturelles" title="Lisez entre les mots." intro="De courtes explorations éditoriales des mondes sociaux contenus dans la langue." /><Cards /></div></section><section className="section topic-index"><div className="container"><p className="eyebrow">Collections à venir</p><h2>Un index culturel en croissance.</h2><div>{frTopics.map((topic) => <span key={topic}>{topic}</span>)}</div></div></section><CTASection eyebrow="La culture devient personnelle" title="Dans quel monde voulez-vous entrer ?" copy="Construisez un Language Map autour des personnes, des lieux, des médias et des questions culturelles qui vous attirent déjà." /></>}
  />;
}
