import type { Metadata } from "next";
import { Localized } from "@/components/localized";
import { CTASection, PageIntro, SectionHeading } from "@/components/ui";

export const metadata: Metadata = { title: "About", description: "Global Speaker grew from self-directed language learning and the idea that language sticks when it connects to real life.", alternates: { canonical: "/about" } };

const values = {
  en: [["Real environments", "Language should return to the places where it will be used."], ["Meaningful situations", "A sentence is easier to keep when there is a reason to say it."], ["Interests", "Curiosity creates attention, repetition, and a personal point of view."], ["Emotion", "Feeling gives language weight and makes memory less mechanical."], ["Identity", "Learning another language should expand who you can be, not erase who you are."], ["Communication", "The point is connection: understanding, responding, and being understood."]],
  es: [["Entornos reales", "El idioma debe volver a los lugares donde realmente se usará."], ["Situaciones con sentido", "Una frase es más fácil de recordar cuando existe una razón para decirla."], ["Intereses", "La curiosidad crea atención, repetición y un punto de vista personal."], ["Emoción", "Sentir le da peso al idioma y vuelve la memoria menos mecánica."], ["Identidad", "Aprender otro idioma debe ampliar quién puedes ser, no borrar quién eres."], ["Comunicación", "El objetivo es conectar: entender, responder y ser entendido."]],
  fr: [["Environnements réels", "La langue doit revenir aux endroits où elle sera réellement utilisée."], ["Situations porteuses de sens", "Une phrase se retient mieux lorsqu'il existe une raison de la dire."], ["Intérêts", "La curiosité crée l'attention, la répétition et un point de vue personnel."], ["Émotion", "Le ressenti donne du poids à la langue et rend la mémoire moins mécanique."], ["Identité", "Apprendre une autre langue doit élargir ce que vous pouvez être, pas effacer qui vous êtes."], ["Communication", "Le but est la connexion : comprendre, répondre et être compris."]],
};

function ValueGrid({ locale }: { locale: keyof typeof values }) { return <div className="values-grid">{values[locale].map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div>; }

export default function AboutPage() {
  return <Localized
    en={<><PageIntro eyebrow="About · The human starting point" title="Built by a language learner." copy="Global Speaker began with a simple observation: language becomes easier to remember when it belongs to a place, a feeling, an interest, or something you genuinely want to say." accent="ink" note="Not a corporate origin story" /><section className="section founder-story"><div className="container founder-story__grid"><div className="founder-image-slot" role="img" aria-label="Reserved portrait space for the Global Speaker founder"><span>Founder portrait</span><i>coming into view</i></div><div className="founder-story__copy"><SectionHeading eyebrow="The origin" title="Learning changed when the world became the textbook." /><p>Years of self-directed language learning revealed a pattern. Vocabulary attached to a real street, a song, a conversation, or an emotional moment stayed alive. Vocabulary isolated on a page often disappeared.</p><p>That insight became a method: begin with the learner’s environments, attention, identity, and communication needs. Then build the language that lets them participate more fully.</p><blockquote>“The goal is not to sound like a textbook. It is to become more yourself in another language.”</blockquote></div></div></section><section className="section values-section"><div className="container"><SectionHeading eyebrow="What stays central" title="Meaning before machinery." /><ValueGrid locale="en" /></div></section><CTASection eyebrow="Your story is source material" title="What do you want to be able to say?" /></>}
    es={<><PageIntro eyebrow="Acerca de · El punto de partida humano" title="Creado por un estudiante de idiomas." copy="Global Speaker nació de una observación sencilla: el idioma se recuerda mejor cuando pertenece a un lugar, una emoción, un interés o algo que de verdad quieres decir." accent="ink" note="No es una historia corporativa de origen" /><section className="section founder-story"><div className="container founder-story__grid"><div className="founder-image-slot" role="img" aria-label="Espacio reservado para el retrato del fundador de Global Speaker"><span>Retrato del fundador</span><i>próximamente</i></div><div className="founder-story__copy"><SectionHeading eyebrow="El origen" title="Aprender cambió cuando el mundo se convirtió en el libro de texto." /><p>Años de aprendizaje autodidacta revelaron un patrón. El vocabulario unido a una calle real, una canción, una conversación o un momento emocional permanecía vivo. El vocabulario aislado en una página solía desaparecer.</p><p>Esa idea se convirtió en un método: empezar por los entornos, la atención, la identidad y las necesidades de comunicación del estudiante. Después construir el idioma que le permite participar con mayor plenitud.</p><blockquote>“La meta no es sonar como un libro de texto. Es poder ser más tú mismo en otro idioma.”</blockquote></div></div></section><section className="section values-section"><div className="container"><SectionHeading eyebrow="Lo que permanece en el centro" title="Sentido antes que maquinaria." /><ValueGrid locale="es" /></div></section><CTASection eyebrow="Tu historia es material de aprendizaje" title="¿Qué quieres ser capaz de decir?" /></>}
    fr={<><PageIntro eyebrow="À propos · Le point de départ humain" title="Créé par un apprenant en langues." copy="Global Speaker est né d'une observation simple : une langue se retient mieux lorsqu'elle appartient à un lieu, une émotion, un intérêt ou quelque chose que vous voulez réellement dire." accent="ink" note="Pas une histoire d'origine corporate" /><section className="section founder-story"><div className="container founder-story__grid"><div className="founder-image-slot" role="img" aria-label="Espace réservé au portrait du fondateur de Global Speaker"><span>Portrait du fondateur</span><i>à venir</i></div><div className="founder-story__copy"><SectionHeading eyebrow="L'origine" title="L'apprentissage a changé lorsque le monde est devenu le manuel." /><p>Des années d'apprentissage autodidacte ont révélé un schéma. Le vocabulaire lié à une vraie rue, une chanson, une conversation ou un moment émotionnel restait vivant. Le vocabulaire isolé sur une page disparaissait souvent.</p><p>Cette idée est devenue une méthode : partir des environnements, de l'attention, de l'identité et des besoins de communication de l'apprenant, puis construire la langue qui lui permet de participer plus pleinement.</p><blockquote>« Le but n'est pas de sonner comme un manuel. C'est de devenir davantage vous-même dans une autre langue. »</blockquote></div></div></section><section className="section values-section"><div className="container"><SectionHeading eyebrow="Ce qui reste central" title="Le sens avant la mécanique." /><ValueGrid locale="fr" /></div></section><CTASection eyebrow="Votre histoire est une matière d'apprentissage" title="Qu'aimeriez-vous pouvoir dire ?" /></>}
  />;
}
