import type { Metadata } from "next";
import { LifeEnvironmentGrid } from "@/components/life-environment-grid";
import { Localized } from "@/components/localized";
import { MethodExample, MethodSequence } from "@/components/method-sequence";
import { CTASection, PageIntro, SectionHeading } from "@/components/ui";

export const metadata: Metadata = { title: "The Global Speaker Method", description: "See how Global Speaker turns perception, thought, environment, and interests into language you can use.", alternates: { canonical: "/method" } };

const principleSets = {
  en: [["Perceive", "Start with what your senses and attention already notice."], ["Think", "Shape observations into opinions, questions, memories, and plans."], ["Connect", "Attach new language to an environment, relationship, or interest."], ["Express", "Build a sentence that sounds like something you would actually say."], ["Interact", "Use it with another person and let the exchange change what comes next."]],
  es: [["Percibir", "Empieza por lo que tus sentidos y tu atención ya notan."], ["Pensar", "Convierte observaciones en opiniones, preguntas, recuerdos y planes."], ["Conectar", "Une el nuevo idioma a un entorno, una relación o un interés."], ["Expresar", "Construye una frase que suene como algo que realmente dirías."], ["Interactuar", "Úsala con otra persona y deja que el intercambio cambie lo que viene después."]],
  fr: [["Percevoir", "Commencez par ce que vos sens et votre attention remarquent déjà."], ["Penser", "Transformez les observations en opinions, questions, souvenirs et projets."], ["Relier", "Attachez la nouvelle langue à un environnement, une relation ou un intérêt."], ["Exprimer", "Construisez une phrase qui ressemble à quelque chose que vous diriez réellement."], ["Interagir", "Utilisez-la avec quelqu'un et laissez l'échange influencer la suite."]],
};

function Principles({ locale }: { locale: keyof typeof principleSets }) { return <div className="method-principles">{principleSets[locale].map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div>; }

export default function MethodPage() {
  return <Localized
    en={<><PageIntro eyebrow="Method · Language follows experience" title="You do not begin with a list of words." copy="You begin with a world you already perceive, think about, care about, and want to share. Language becomes the bridge." accent="ink" note="Self → world → voice" /><section className="section"><div className="container"><SectionHeading eyebrow="The sequence" title="From noticing to belonging." intro="Each stage gives the next one a reason to exist." /><MethodSequence /><Principles locale="en" /></div></section><section className="section method-live"><div className="container"><SectionHeading eyebrow="A live example" title="One view. A chain of language." intro="The sentence at the end matters because every step before it is human." /><MethodExample /></div></section><section className="section life-section"><div className="container"><SectionHeading eyebrow="Your source material" title="The curriculum is already around you." intro="Open an environment and notice how much language it contains." /><LifeEnvironmentGrid /></div></section><CTASection title="Turn your world into a learning path." /></>}
    es={<><PageIntro eyebrow="Método · El idioma sigue a la experiencia" title="No empiezas con una lista de palabras." copy="Empiezas con un mundo que ya percibes, piensas, valoras y quieres compartir. El idioma se convierte en el puente." accent="ink" note="Yo → mundo → voz" /><section className="section"><div className="container"><SectionHeading eyebrow="La secuencia" title="De notar a pertenecer." intro="Cada etapa le da a la siguiente una razón para existir." /><MethodSequence /><Principles locale="es" /></div></section><section className="section method-live"><div className="container"><SectionHeading eyebrow="Un ejemplo vivo" title="Una mirada. Una cadena de lenguaje." intro="La frase final importa porque cada paso anterior es humano." /><MethodExample /></div></section><section className="section life-section"><div className="container"><SectionHeading eyebrow="Tu material de origen" title="El currículo ya está a tu alrededor." intro="Abre un entorno y observa cuánto lenguaje contiene." /><LifeEnvironmentGrid /></div></section><CTASection title="Convierte tu mundo en una ruta de aprendizaje." /></>}
    fr={<><PageIntro eyebrow="Méthode · La langue suit l'expérience" title="Vous ne commencez pas par une liste de mots." copy="Vous commencez par un monde que vous percevez déjà, auquel vous pensez, qui compte pour vous et que vous voulez partager. La langue devient le pont." accent="ink" note="Soi → monde → voix" /><section className="section"><div className="container"><SectionHeading eyebrow="La séquence" title="De l'attention à l'appartenance." intro="Chaque étape donne à la suivante une raison d'exister." /><MethodSequence /><Principles locale="fr" /></div></section><section className="section method-live"><div className="container"><SectionHeading eyebrow="Un exemple concret" title="Un regard. Une chaîne de langage." intro="La phrase finale compte parce que chaque étape précédente est humaine." /><MethodExample /></div></section><section className="section life-section"><div className="container"><SectionHeading eyebrow="Votre matière première" title="Le programme est déjà autour de vous." intro="Ouvrez un environnement et remarquez toute la langue qu'il contient." /><LifeEnvironmentGrid /></div></section><CTASection title="Transformez votre monde en parcours d'apprentissage." /></>}
  />;
}
