import type { Metadata } from "next";
import { Localized } from "@/components/localized";
import { ButtonLink, CTASection, PageIntro, SectionHeading } from "@/components/ui";

export const metadata: Metadata = { title: "Language Learning in Tulum", description: "English, French, and Spanish learning in Tulum and the Riviera Maya for work, hospitality, daily life, and connection.", alternates: { canonical: "/locations/tulum" } };

const audiences={
 en:[["Hospitality","Welcome guests, solve problems, explain places, and create trust."],["Tourism","Guide, recommend, tell stories, and respond clearly."],["Living in Mexico","Participate in daily life, relationships, services, and community."],["Professionals","Meet, present, negotiate, collaborate, and follow up."],["Long-stay travelers","Move beyond transactions into genuine interaction."],["Personal learning","Learn through culture, music, food, people, and place."]],
 es:[["Hospitalidad","Recibe huéspedes, resuelve problemas, explica lugares y crea confianza."],["Turismo","Guía, recomienda, cuenta historias y responde con claridad."],["Vivir en México","Participa en la vida diaria, relaciones, servicios y comunidad."],["Profesionales","Reúnete, presenta, negocia, colabora y da seguimiento."],["Viajeros de larga estancia","Ve más allá de las transacciones hacia una interacción genuina."],["Aprendizaje personal","Aprende a través de cultura, música, comida, personas y lugar."]],
 fr:[["Hôtellerie","Accueillez les clients, résolvez les problèmes, expliquez les lieux et créez la confiance."],["Tourisme","Guidez, recommandez, racontez et répondez clairement."],["Vivre au Mexique","Participez à la vie quotidienne, aux relations, aux services et à la communauté."],["Professionnels","Rencontrez, présentez, négociez, collaborez et assurez le suivi."],["Voyageurs longue durée","Dépassez les transactions pour entrer dans une interaction authentique."],["Apprentissage personnel","Apprenez à travers la culture, la musique, la cuisine, les personnes et le lieu."]]
} as const;

function Body({locale}:{locale:"en"|"es"|"fr"}){const text={
 en:{eye:"Tulum · Riviera Maya",title:"Speak the language of where you live.",copy:"English, French, and Spanish learning shaped by the real conversations of work, community, travel, and daily life in the Riviera Maya.",note:"Local roots · International outlook",cross:"A place of crossings",many:"Many worlds meet here.",intro:"Tulum is local and international at once. Hospitality teams welcome visitors from everywhere. People arrive to travel, work, build businesses, or create a new life. Language is not an abstract subject here — it is part of the day.",p:"Global Speaker uses that reality without turning the entire brand into a destination cliché. The local environment is rich source material; the method travels anywhere.",relevant:"Made relevant",moments:"Language for the moments around you.",english:"Explore English",spanish:"Explore Spanish",ctaEye:"Start locally",ctaTitle:"Map the language your life in Tulum needs.",ctaCopy:"Tell us about your role, routines, relationships, and the conversations you want to join."},
 es:{eye:"Tulum · Riviera Maya",title:"Habla el idioma del lugar donde vives.",copy:"Aprendizaje de inglés, francés y español moldeado por las conversaciones reales del trabajo, la comunidad, los viajes y la vida diaria en la Riviera Maya.",note:"Raíces locales · Mirada internacional",cross:"Un lugar de cruces",many:"Aquí se encuentran muchos mundos.",intro:"Tulum es local e internacional al mismo tiempo. Los equipos de hospitalidad reciben visitantes de todas partes. La gente llega a viajar, trabajar, construir negocios o crear una nueva vida. Aquí el idioma no es una materia abstracta: forma parte del día.",p:"Global Speaker aprovecha esa realidad sin convertir toda la marca en un cliché de destino. El entorno local es una fuente rica de material; el método puede viajar a cualquier lugar.",relevant:"Hecho relevante",moments:"Idioma para los momentos que te rodean.",english:"Explorar inglés",spanish:"Explorar español",ctaEye:"Empieza localmente",ctaTitle:"Mapea el idioma que necesita tu vida en Tulum.",ctaCopy:"Cuéntanos sobre tu rol, rutinas, relaciones y las conversaciones a las que quieres unirte."},
 fr:{eye:"Tulum · Riviera Maya",title:"Parlez la langue du lieu où vous vivez.",copy:"Apprentissage de l’anglais, du français et de l’espagnol façonné par les conversations réelles du travail, de la communauté, du voyage et de la vie quotidienne dans la Riviera Maya.",note:"Racines locales · Regard international",cross:"Un lieu de croisements",many:"De nombreux mondes se rencontrent ici.",intro:"Tulum est à la fois local et international. Les équipes d’hôtellerie accueillent des visiteurs du monde entier. Les gens arrivent pour voyager, travailler, créer des entreprises ou commencer une nouvelle vie. Ici, la langue n’est pas une matière abstraite : elle fait partie du quotidien.",p:"Global Speaker utilise cette réalité sans transformer toute la marque en cliché de destination. L’environnement local offre une matière riche ; la méthode peut voyager partout.",relevant:"Rendu pertinent",moments:"La langue pour les moments qui vous entourent.",english:"Explorer l’anglais",spanish:"Explorer l’espagnol",ctaEye:"Commencez localement",ctaTitle:"Cartographiez la langue dont votre vie à Tulum a besoin.",ctaCopy:"Parlez-nous de votre rôle, de vos habitudes, de vos relations et des conversations auxquelles vous voulez participer."}
}[locale];return <><PageIntro eyebrow={text.eye} title={text.title} copy={text.copy} accent="terracotta" note={text.note}/><section className="section location-story"><div className="container location-story__grid"><div className="location-story__visual" aria-label="Tulum conversation atlas"><span className="location-story__coordinates">20.2114° N<br/>87.4654° W</span><div className="location-story__atlas"><span><i>01</i>Welcome</span><span><i>02</i>Explain</span><span><i>03</i>Belong</span></div><b>Conversation<br/>atlas</b><strong>Tulum · Riviera Maya</strong></div><div><SectionHeading eyebrow={text.cross} title={text.many} intro={text.intro}/><p>{text.p}</p></div></div></section><section className="section local-audiences"><div className="container"><SectionHeading eyebrow={text.relevant} title={text.moments}/><div className="audience-grid">{audiences[locale].map(([title,copy],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="local-actions"><ButtonLink href="/learn/english">{text.english}</ButtonLink><ButtonLink href="/learn/spanish" variant="secondary">{text.spanish}</ButtonLink></div></div></section><CTASection eyebrow={text.ctaEye} title={text.ctaTitle} copy={text.ctaCopy}/></>}

export default function TulumPage(){const schema={"@context":"https://schema.org","@type":"Service",name:"Global Speaker language learning in Tulum",serviceType:"English, French, and Spanish language learning",areaServed:["Tulum","Riviera Maya"],provider:{"@type":"Organization",name:"Global Speaker"}};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/><Localized en={<Body locale="en"/>} es={<Body locale="es"/>} fr={<Body locale="fr"/>}/></>}
