import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { CurriculumMarkdown } from "@/components/curriculum-markdown";
import { ButtonLink } from "@/components/ui";
import { getAuthoredCurriculumLesson, getCurriculumLessonById, getCurriculumLessonMeta, getCurriculumLessons } from "@/lib/curriculum";
import { getInterfaceLocale } from "@/lib/interface-locale-server";
import { siteConfig } from "@/config/site";

const languageLabels = { english: "English", spanish: "Español", french: "Français" } as const;
const languageCodes = { english: "en", spanish: "es", french: "fr" } as const;
const lessonUi = {
  en:{path:"learning path",practice:"Practice time",level:"Level",environment:"Environment",inLesson:"In this lesson",make:"Make it yours",mapTitle:"Connect this lesson to your Language Map.",mapCopy:"Use the situation, environment, and communication goal to turn this lesson into something from your real life.",mapButton:"Open my Language Map",continueEye:"Continue the graph",continueTitle:"Keep moving through the curriculum."},
  es:{path:"ruta de aprendizaje",practice:"Tiempo de práctica",level:"Nivel",environment:"Entorno",inLesson:"En esta lección",make:"Hazlo tuyo",mapTitle:"Conecta esta lección con tu Mapa de Idioma.",mapCopy:"Usa la situación, el entorno y el objetivo comunicativo para llevar esta lección a algo real de tu vida.",mapButton:"Abrir mi Mapa de Idioma",continueEye:"Continúa el recorrido",continueTitle:"Sigue avanzando por el currículo."},
  fr:{path:"parcours d’apprentissage",practice:"Temps de pratique",level:"Niveau",environment:"Contexte",inLesson:"Dans cette leçon",make:"À vous de jouer",mapTitle:"Reliez cette leçon à votre carte linguistique.",mapCopy:"Utilisez la situation, le contexte et l’objectif communicatif pour relier cette leçon à votre vie réelle.",mapButton:"Ouvrir ma carte linguistique",continueEye:"Poursuivre le parcours",continueTitle:"Continuez à avancer dans le programme."}
} as const;
const sections = {
  en:{},
  es:{Context:"Contexto",Objective:"Objetivo",Notice:"Observa",Understand:"Comprende","Language toolkit":"Herramientas lingüísticas",Examples:"Ejemplos","Culture & register":"Cultura y registro","Guided practice":"Práctica guiada",Production:"Producción","Real-world challenge":"Reto en la vida real",Reflection:"Reflexión",Continue:"Continúa"},
  fr:{Context:"Contexte",Objective:"Objectif",Notice:"Observer",Understand:"Comprendre","Language toolkit":"Boîte à outils linguistique",Examples:"Exemples","Culture & register":"Culture et registre","Guided practice":"Pratique guidée",Production:"Production","Real-world challenge":"Défi dans la vie réelle",Reflection:"Réflexion",Continue:"Continuer"}
} as const;

export function generateStaticParams(){ return getCurriculumLessons().map((lesson)=>({language:lesson.language,slug:lesson.slug})); }
export async function generateMetadata({params}:PageProps<"/learn/[language]/[slug]">):Promise<Metadata>{ const {language,slug}=await params; const lesson=getCurriculumLessonMeta(language,slug); if(!lesson)return{}; return{title:lesson.seo.title,description:lesson.seo.description,alternates:{canonical:lesson.seo.canonicalPath},robots:lesson.seo.indexable?undefined:{index:false,follow:true},openGraph:{type:"article",title:lesson.title,description:lesson.description,url:lesson.seo.canonicalPath}}; }

export default async function CurriculumLessonPage({params}:PageProps<"/learn/[language]/[slug]">){
  const {language,slug}=await params; const locale=await getInterfaceLocale(); const lesson=getAuthoredCurriculumLesson(language,slug); if(!lesson)notFound();
  const relatedIds=[...lesson.relatedLessons,...lesson.nextRecommended].map((r)=>r.id).filter((id,i,list)=>list.indexOf(id)===i).slice(0,4);
  const related=relatedIds.map(getCurriculumLessonById).filter((item)=>item!==undefined); const languageLabel=languageLabels[lesson.language]; const ui=lessonUi[locale]; const translated=sections[locale] as Record<string,string>; const display=(heading:string)=>translated[heading]??heading;
  const schema={"@context":"https://schema.org","@type":"LearningResource",name:lesson.title,description:lesson.description,learningResourceType:lesson.lessonType,educationalLevel:lesson.level,inLanguage:languageCodes[lesson.language],provider:{"@type":"Organization",name:"Global Speaker"},url:`${siteConfig.siteUrl}${lesson.seo.canonicalPath}`};
  return <article className="article article--teal" lang={languageCodes[lesson.language]}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/><header className="article-header"><div className="container article-header__grid"><div><Link className="article-back" href={`/learn/${lesson.language}`}>← {languageLabel} {ui.path}</Link><p className="eyebrow">{languageLabel} · {lesson.level} · {lesson.lessonType.replaceAll("-"," ")}</p><h1>{lesson.title}</h1><p className="article-header__subtitle">{lesson.learningObjective}</p></div><div className="article-header__aside"><dl><div><dt>{ui.practice}</dt><dd>{lesson.estimatedMinutes} min</dd></div><div><dt>{ui.level}</dt><dd>{lesson.level}</dd></div><div><dt>{ui.environment}</dt><dd>{lesson.primaryEnvironment}</dd></div></dl></div></div></header><div className="container article-layout"><aside className="article-rail"><span>{ui.inLesson}</span>{lesson.sections.map((section,index)=><a key={section.heading} href={`#section-${index+1}`}>{String(index+1).padStart(2,"0")} {display(section.heading)}</a>)}</aside><div className="article-content"><p className="article-intro">{lesson.description}</p>{lesson.sections.map((section,index)=><section id={`section-${index+1}`} key={`${index}-${section.heading}`}><span className="article-section-number">{String(index+1).padStart(2,"0")}</span><h2>{display(section.heading)}</h2><CurriculumMarkdown body={section.body}/></section>)}<section className="article-map-cta"><div><p className="eyebrow">{ui.make}</p><h2>{ui.mapTitle}</h2><p>{ui.mapCopy}</p></div><ButtonLink href="/language-map">{ui.mapButton}</ButtonLink></section></div></div>{related.length?<section className="section related-resources"><div className="container"><p className="eyebrow">{ui.continueEye}</p><h2>{ui.continueTitle}</h2><div className="resource-grid">{related.map((item)=><Link className="resource-card" key={item.id} href={`/learn/${item.language}/${item.slug}`}><p className="eyebrow">{languageLabels[item.language]} · {item.level}</p><h3>{item.title}</h3><p>{item.learningObjective}</p></Link>)}</div></div></section>:null}</article>;
}
