"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import type { FormEvent, ReactNode } from "react";
import { useInterfaceLocale } from "@/components/interface-locale";
import { contactConfig } from "@/config/site";
import { buildWhatsAppUrl, formatLanguageMapMessage, type LanguageMapData } from "@/lib/language-map";
import { pickLocaleCopy } from "@/lib/locale-copy";

const copy = {
  en: {
    reasons:["Work","Travel","Living abroad","Relationships","Culture","Personal growth","Other"], challenges:["Speaking","Understanding","Vocabulary","Grammar","Pronunciation","Confidence","Other"], levels:["Beginner","Basic","Intermediate","Advanced","Not sure"],
    chooseOne:"Choose at least one area you want to strengthen.", readyEye:"Personal Language Map · Ready", readyTitle:"Your Language Map is ready.", readyCopy:"You have turned the life you already live into a clear starting point for learning.", starting:"Starting point", language:"Language", goal:"Goal", level:"Level", contexts:"Real contexts", focus:"Focus", interests:"Interests", nextEye:"Your next conversation", nextTitle:"Ready to turn this into a learning plan?", nextCopy:"Nothing has been sent yet. WhatsApp opens with your map already prepared; you decide whether to send it.", whatsapp:"Continue on WhatsApp", pending:"WhatsApp setup pending", copyMap:"Copy my Language Map", copied:"Copied", failed:"Copy failed — try again", edit:"Edit my Language Map", copiedMsg:"Your Language Map has been copied.", failedMsg:"Your browser blocked clipboard access. Select and copy the summary manually.", learn:"What do you want to learn?", why:"Why?", where:"Where do you use or want to use the language?", whereHelp:"Think about places, people, routines, or moments.", wherePlaceholder:"At work with hotel guests, with friends, when I travel…", interestQ:"What interests you?", interestHelp:"Your interests make new language easier to remember.", interestPlaceholder:"Music, food, films, nature, technology…", hardest:"What feels hardest right now?", approx:"Current approximate level", name:"What should we call you?", nameHelp:"This personalizes your map. No contact details are collected here.", namePlaceholder:"Your name", privacy:"Your answers stay in this browser until you choose to continue on WhatsApp. Global Speaker does not store or silently send this map.", create:"Create my Language Map"
  },
  es: {
    reasons:["Trabajo","Viajes","Vivir en el extranjero","Relaciones","Cultura","Crecimiento personal","Otro"], challenges:["Hablar","Comprender","Vocabulario","Gramática","Pronunciación","Confianza","Otro"], levels:["Principiante","Básico","Intermedio","Avanzado","No estoy seguro"],
    chooseOne:"Elige al menos un área que quieras fortalecer.", readyEye:"Mapa de Idioma Personal · Listo", readyTitle:"Tu Mapa de Idioma está listo.", readyCopy:"Convertiste la vida que ya vives en un punto de partida claro para aprender.", starting:"Punto de partida", language:"Idioma", goal:"Meta", level:"Nivel", contexts:"Contextos reales", focus:"Enfoque", interests:"Intereses", nextEye:"Tu próxima conversación", nextTitle:"¿Listo para convertir esto en un plan de aprendizaje?", nextCopy:"Todavía no se ha enviado nada. WhatsApp se abre con tu mapa preparado; tú decides si lo envías.", whatsapp:"Continuar por WhatsApp", pending:"Configuración de WhatsApp pendiente", copyMap:"Copiar mi Mapa de Idioma", copied:"Copiado", failed:"No se pudo copiar — intenta de nuevo", edit:"Editar mi Mapa de Idioma", copiedMsg:"Tu Mapa de Idioma fue copiado.", failedMsg:"Tu navegador bloqueó el portapapeles. Selecciona y copia el resumen manualmente.", learn:"¿Qué quieres aprender?", why:"¿Por qué?", where:"¿Dónde usas o quieres usar el idioma?", whereHelp:"Piensa en lugares, personas, rutinas o momentos.", wherePlaceholder:"En el trabajo con huéspedes, con amigos, cuando viajo…", interestQ:"¿Qué te interesa?", interestHelp:"Tus intereses hacen que el idioma nuevo sea más fácil de recordar.", interestPlaceholder:"Música, comida, películas, naturaleza, tecnología…", hardest:"¿Qué se siente más difícil ahora?", approx:"Nivel aproximado actual", name:"¿Cómo debemos llamarte?", nameHelp:"Esto personaliza tu mapa. Aquí no recopilamos datos de contacto.", namePlaceholder:"Tu nombre", privacy:"Tus respuestas permanecen en este navegador hasta que decidas continuar por WhatsApp. Global Speaker no guarda ni envía este mapa silenciosamente.", create:"Crear mi Mapa de Idioma"
  },
  fr: {
    reasons:["Travail","Voyage","Vivre à l’étranger","Relations","Culture","Développement personnel","Autre"], challenges:["Parler","Comprendre","Vocabulaire","Grammaire","Prononciation","Confiance","Autre"], levels:["Débutant","Élémentaire","Intermédiaire","Avancé","Je ne sais pas"],
    chooseOne:"Choisissez au moins un domaine à renforcer.", readyEye:"Carte linguistique personnelle · Prête", readyTitle:"Votre carte linguistique est prête.", readyCopy:"Vous avez transformé votre vie réelle en point de départ clair pour apprendre.", starting:"Point de départ", language:"Langue", goal:"Objectif", level:"Niveau", contexts:"Contextes réels", focus:"Priorités", interests:"Centres d’intérêt", nextEye:"Votre prochaine conversation", nextTitle:"Prêt à transformer cela en plan d’apprentissage ?", nextCopy:"Rien n’a encore été envoyé. WhatsApp s’ouvre avec votre carte déjà préparée ; vous choisissez de l’envoyer ou non.", whatsapp:"Continuer sur WhatsApp", pending:"Configuration WhatsApp en attente", copyMap:"Copier ma carte linguistique", copied:"Copié", failed:"Échec de la copie — réessayez", edit:"Modifier ma carte linguistique", copiedMsg:"Votre carte linguistique a été copiée.", failedMsg:"Votre navigateur a bloqué le presse-papiers. Sélectionnez et copiez le résumé manuellement.", learn:"Quelle langue voulez-vous apprendre ?", why:"Pourquoi ?", where:"Où utilisez-vous ou voulez-vous utiliser la langue ?", whereHelp:"Pensez aux lieux, personnes, habitudes ou moments.", wherePlaceholder:"Au travail avec des clients, avec des amis, en voyage…", interestQ:"Qu’est-ce qui vous intéresse ?", interestHelp:"Vos centres d’intérêt rendent la nouvelle langue plus facile à mémoriser.", interestPlaceholder:"Musique, cuisine, cinéma, nature, technologie…", hardest:"Qu’est-ce qui vous semble le plus difficile aujourd’hui ?", approx:"Niveau approximatif actuel", name:"Comment devons-nous vous appeler ?", nameHelp:"Cela personnalise votre carte. Aucune coordonnée n’est recueillie ici.", namePlaceholder:"Votre nom", privacy:"Vos réponses restent dans ce navigateur jusqu’à ce que vous choisissiez de continuer sur WhatsApp. Global Speaker ne stocke ni n’envoie cette carte en silence.", create:"Créer ma carte linguistique"
  }
} as const;

const languageChoices = ["English", "French", "Spanish"];

function ChoiceGroup({ legend, name, choices, initialValue, multiple = false, error }: { legend: string; name: string; choices: readonly string[]; initialValue?: string | string[]; multiple?: boolean; error?: string }) {
  const selectedValues = Array.isArray(initialValue) ? initialValue : initialValue ? [initialValue] : [];
  return <fieldset className="choice-group" aria-describedby={error ? `${name}-error` : undefined}><legend>{legend}</legend><div>{choices.map((choice) => <label key={choice}><input type={multiple ? "checkbox" : "radio"} name={name} value={choice} required={!multiple} defaultChecked={selectedValues.includes(choice)} /><span>{choice}</span></label>)}</div>{error ? <p className="form-error" id={`${name}-error`} role="alert">{error}</p> : null}</fieldset>;
}
function SummaryItem({ label, children }: { label: string; children: ReactNode }) { return <div><dt>{label}</dt><dd>{children}</dd></div>; }

export function LanguageMapForm() {
  const { locale } = useInterfaceLocale();
  const c = pickLocaleCopy(copy, locale);
  const [completedMap, setCompletedMap] = useState<LanguageMapData | null>(null);
  const [draftMap, setDraftMap] = useState<LanguageMapData | null>(null);
  const [challengeError, setChallengeError] = useState("");
  const [copyState, setCopyState] = useState<"idle"|"copied"|"failed">("idle");
  const completionHeading = useRef<HTMLHeadingElement>(null);
  const message = useMemo(() => completedMap ? formatLanguageMapMessage(completedMap) : "", [completedMap]);
  const whatsappUrl = useMemo(() => buildWhatsAppUrl(contactConfig.whatsappNumber, message), [message]);
  useEffect(() => { if (completedMap) completionHeading.current?.focus(); }, [completedMap]);

  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const formData = new FormData(event.currentTarget); const selectedChallenges = formData.getAll("challenge").map(String);
    if (!selectedChallenges.length) { setChallengeError(c.chooseOne); document.querySelector<HTMLInputElement>('input[name="challenge"]')?.focus(); return; }
    const nextMap = { language:String(formData.get("language")??""), goal:String(formData.get("reason")??""), environments:String(formData.get("environments")??""), interests:String(formData.get("interests")??""), challenges:selectedChallenges, level:String(formData.get("level")??""), name:String(formData.get("name")??"") };
    setChallengeError(""); setCopyState("idle"); setDraftMap(nextMap); setCompletedMap(nextMap); window.scrollTo({top:0,behavior:"smooth"});
  }
  function editMap(){ setCompletedMap(null); setCopyState("idle"); requestAnimationFrame(()=>document.querySelector(".language-map-form")?.scrollIntoView({block:"start"})); }
  async function copyMap(){ try{ await navigator.clipboard.writeText(message); setCopyState("copied"); }catch{ setCopyState("failed"); } }

  if(completedMap) return <section className="map-completion" aria-labelledby="map-completion-title"><div className="map-completion__intro"><p className="eyebrow">{c.readyEye}</p><h2 id="map-completion-title" ref={completionHeading} tabIndex={-1}>{c.readyTitle}</h2><p>{c.readyCopy}</p></div><div className="map-completion__artifact"><header><span>Global Speaker · Language Map</span><span>GS—YOU</span></header><div className="map-completion__you"><span>{c.starting}</span><strong>{completedMap.name}</strong><i>{completedMap.language}</i></div><dl className="map-completion__summary"><SummaryItem label={c.language}>{completedMap.language}</SummaryItem><SummaryItem label={c.goal}>{completedMap.goal}</SummaryItem><SummaryItem label={c.level}>{completedMap.level}</SummaryItem><SummaryItem label={c.contexts}>{completedMap.environments}</SummaryItem><SummaryItem label={c.focus}>{completedMap.challenges.join(" · ")}</SummaryItem><SummaryItem label={c.interests}>{completedMap.interests}</SummaryItem></dl></div><div className="map-completion__handoff"><div><p className="eyebrow">{c.nextEye}</p><h3>{c.nextTitle}</h3><p>{c.nextCopy}</p></div><div className="map-completion__actions">{whatsappUrl ? <a className="button button--primary" href={whatsappUrl} target="_blank" rel="noreferrer"><span>{c.whatsapp}</span><span aria-hidden="true">↗</span></a> : <button className="button button--primary" type="button" disabled><span>{c.pending}</span></button>}<button className="button button--secondary" type="button" onClick={copyMap}><span>{copyState==="copied"?c.copied:copyState==="failed"?c.failed:c.copyMap}</span><span aria-hidden="true">{copyState==="copied"?"✓":"⧉"}</span></button><button className="map-completion__edit" type="button" onClick={editMap}>{c.edit}</button></div><p className="copy-feedback" aria-live="polite">{copyState==="copied"?c.copiedMsg:copyState==="failed"?c.failedMsg:""}</p></div></section>;

  return <form className="language-map-form" onSubmit={handleSubmit}><div className="form-section"><div className="form-section__number">01</div><div className="form-section__body"><ChoiceGroup legend={c.learn} name="language" choices={languageChoices} initialValue={draftMap?.language}/><ChoiceGroup legend={c.why} name="reason" choices={c.reasons} initialValue={draftMap?.goal}/></div></div><div className="form-section"><div className="form-section__number">02</div><div className="form-section__body form-fields"><label htmlFor="environments">{c.where}<span>{c.whereHelp}</span></label><textarea id="environments" name="environments" rows={4} required defaultValue={draftMap?.environments} placeholder={c.wherePlaceholder}/><label htmlFor="interests">{c.interestQ}<span>{c.interestHelp}</span></label><textarea id="interests" name="interests" rows={3} required defaultValue={draftMap?.interests} placeholder={c.interestPlaceholder}/></div></div><div className="form-section"><div className="form-section__number">03</div><div className="form-section__body"><ChoiceGroup legend={c.hardest} name="challenge" choices={c.challenges} initialValue={draftMap?.challenges} multiple error={challengeError}/><ChoiceGroup legend={c.approx} name="level" choices={c.levels} initialValue={draftMap?.level}/></div></div><div className="form-section"><div className="form-section__number">04</div><div className="form-section__body form-fields form-fields--identity"><label htmlFor="name">{c.name}<span>{c.nameHelp}</span></label><input id="name" name="name" autoComplete="name" required defaultValue={draftMap?.name} placeholder={c.namePlaceholder}/></div></div><div className="form-submit"><p>{c.privacy}</p><button className="button button--primary" type="submit"><span>{c.create}</span><span aria-hidden="true">↗</span></button></div></form>;
}
