import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ResourceCard } from "@/components/cards";
import { MethodSequence } from "@/components/method-sequence";
import { ButtonLink, CTASection, PageIntro, SectionHeading } from "@/components/ui";
import { getLocalizedCurriculumOverride, getLocalizedFoundationLessonIds } from "@/content/curriculum-localized";
import { resources } from "@/content/resources";
import { activeLanguages, languages, type LanguageKey } from "@/content/site";
import { getPolyglotArticlesForLanguage, polyglotTopics } from "@/content/polyglot";
import { getCurriculumLessonById, getCurriculumLessons, type CurriculumLanguage } from "@/lib/curriculum";
import type { InterfaceLocale } from "@/lib/interface-locale";
import { getInterfaceLocale } from "@/lib/interface-locale-server";
import { pickLocaleCopy, type WithEnglish } from "@/lib/locale-copy";

const cefrOrder = ["A1", "A2", "B1", "B2", "C1", "C2"] as const;
const areaSlugs = ["home", "work", "people", "travel", "interests", "culture"] as const;
type AreaSlug = (typeof areaSlugs)[number];
type HeroCopy = { eyebrow: string; title: string; copy: string };

const areaCopy: WithEnglish<Record<AreaSlug, [string, string]>> = {
  en: { home: ["Home", "Routines · space · shared life"], work: ["Work", "Tasks · clients · decisions"], people: ["People", "Connection · opinions · boundaries"], travel: ["Travel", "Arrival · movement · problem-solving"], interests: ["Interests", "Music · technology · food · ideas"], culture: ["Culture", "Register · humor · implication"] },
  es: { home: ["Hogar", "Rutinas · espacio · vida compartida"], work: ["Trabajo", "Tareas · clientes · decisiones"], people: ["Personas", "Conexión · opiniones · límites"], travel: ["Viajes", "Llegada · movimiento · resolución de problemas"], interests: ["Intereses", "Música · tecnología · comida · ideas"], culture: ["Cultura", "Registro · humor · implicación"] },
  fr: { home: ["Maison", "Routines · espace · vie partagée"], work: ["Travail", "Tâches · clients · décisions"], people: ["Personnes", "Lien · opinions · limites"], travel: ["Voyage", "Arrivée · déplacements · résolution de problèmes"], interests: ["Centres d’intérêt", "Musique · technologie · cuisine · idées"], culture: ["Culture", "Registre · humour · implicite"] },
  de: { home: ["Zuhause", "Routinen · Raum · Zusammenleben"], work: ["Arbeit", "Aufgaben · Kunden · Entscheidungen"], people: ["Menschen", "Verbindung · Meinungen · Grenzen"], travel: ["Reisen", "Ankunft · Bewegung · Problemlösung"], interests: ["Interessen", "Musik · Technologie · Essen · Ideen"], culture: ["Kultur", "Register · Humor · Andeutungen"] },
  it: { home: ["Casa", "Routine · spazio · vita condivisa"], work: ["Lavoro", "Compiti · clienti · decisioni"], people: ["Persone", "Connessione · opinioni · confini"], travel: ["Viaggi", "Arrivo · spostamenti · problemi"], interests: ["Interessi", "Musica · tecnologia · cibo · idee"], culture: ["Cultura", "Registro · umorismo · impliciti"] },
  pt: { home: ["Casa", "Rotinas · espaço · vida compartilhada"], work: ["Trabalho", "Tarefas · clientes · decisões"], people: ["Pessoas", "Conexão · opiniões · limites"], travel: ["Viagem", "Chegada · deslocamento · resolução de problemas"], interests: ["Interesses", "Música · tecnologia · comida · ideias"], culture: ["Cultura", "Registro · humor · subentendidos"] },
};

const heroCopy: WithEnglish<Partial<Record<LanguageKey, HeroCopy>>> = {
  en: { english: { eyebrow: "English · Real communication", title: "Build an English voice that belongs to you.", copy: "Start with who you are, what you need, and the situations where English becomes useful." }, french: { eyebrow: "French · Real communication", title: "French for expressing your own life.", copy: "Build from identity and immediate needs toward conversation, interests, and social confidence." }, spanish: { eyebrow: "Spanish · Real communication", title: "Spanish for participating in real life.", copy: "Connect personal expression with the situations, relationships, and cultural choices that matter to you." } },
  es: { english: { eyebrow: "Inglés · Comunicación real", title: "Inglés para construir una voz propia.", copy: "Empieza por quién eres, lo que necesitas y las situaciones donde el inglés puede ayudarte." }, french: { eyebrow: "Francés · Comunicación real", title: "Francés para hablar desde tu propia vida.", copy: "Construye desde tu identidad y tus necesidades hasta la conversación y la confianza social." }, spanish: { eyebrow: "Español · Comunicación real", title: "Español para participar en situaciones reales.", copy: "Conecta la expresión personal con las relaciones y decisiones culturales que forman tu vida." } },
  fr: { english: { eyebrow: "Anglais · Communication réelle", title: "L’anglais pour construire votre propre voix.", copy: "Commencez par qui vous êtes, ce dont vous avez besoin et les situations où l’anglais devient utile." }, french: { eyebrow: "Français · Communication réelle", title: "Le français pour exprimer votre propre vie.", copy: "Construisez à partir de votre identité et de vos besoins vers la conversation et la confiance sociale." }, spanish: { eyebrow: "Espagnol · Communication réelle", title: "L’espagnol pour participer à la vie réelle.", copy: "Reliez votre expression personnelle aux situations et relations qui comptent pour vous." } },
  de: { english: { eyebrow: "Englisch · Echte Kommunikation", title: "Entwickle eine englische Stimme, die zu dir gehört.", copy: "Beginne mit dem, was dich ausmacht, was du brauchst und in welchen Situationen Englisch für dich nützlich wird." }, french: { eyebrow: "Französisch · Echte Kommunikation", title: "Französisch, um dein eigenes Leben auszudrücken.", copy: "Baue von deiner Identität und deinen unmittelbaren Bedürfnissen aus hin zu Gesprächen, deinen Interessen und mehr Sicherheit im sozialen Austausch." }, spanish: { eyebrow: "Spanisch · Echte Kommunikation", title: "Spanisch, um am echten Leben teilzunehmen.", copy: "Verbinde deinen persönlichen Ausdruck mit den Situationen, Beziehungen und kulturellen Entscheidungen, die für dich wichtig sind." } },
  it: { english: { eyebrow: "Inglese · Comunicazione reale", title: "Costruisci una voce in inglese che sia davvero tua.", copy: "Parti da chi sei, da ciò di cui hai bisogno e dalle situazioni in cui l’inglese diventa utile per te." }, french: { eyebrow: "Francese · Comunicazione reale", title: "Il francese per esprimere la tua vita.", copy: "Parti dalla tua identità e dai tuoi bisogni immediati per arrivare alla conversazione, ai tuoi interessi e alla sicurezza nelle relazioni sociali." }, spanish: { eyebrow: "Spagnolo · Comunicazione reale", title: "Lo spagnolo per partecipare alla vita reale.", copy: "Collega ciò che vuoi esprimere alle situazioni, alle relazioni e alle scelte culturali che contano per te." } },
  pt: { english: { eyebrow: "Inglês · Comunicação real", title: "Construa uma voz em inglês que seja sua.", copy: "Comece por quem você é, pelo que precisa e pelas situações em que o inglês se torna útil para você." }, french: { eyebrow: "Francês · Comunicação real", title: "Francês para expressar a sua própria vida.", copy: "Parta da sua identidade e das suas necessidades imediatas até chegar à conversa, aos seus interesses e à confiança nas relações sociais." }, spanish: { eyebrow: "Espanhol · Comunicação real", title: "Espanhol para participar da vida real.", copy: "Conecte sua expressão pessoal às situações, relações e escolhas culturais que são importantes para você." } },
};

const hubExamples: WithEnglish<Partial<Record<LanguageKey, string[]>>> = {
  en: { english: ["Say who you are", "Describe your personality", "Handle what matters now", "Share your interests"], french: ["Say who you are", "Describe your personality", "Ask for help clearly", "Turn interests into conversation"], spanish: ["Say who you are", "Build relationships", "Handle immediate needs", "Participate through your interests"] },
  es: { english: ["Decir quién eres", "Describir tu personalidad", "Resolver lo que importa ahora", "Compartir tus intereses"], french: ["Decir quién eres", "Describir tu personalidad", "Pedir ayuda con claridad", "Convertir intereses en conversación"], spanish: ["Decir quién eres", "Construir relaciones", "Resolver necesidades inmediatas", "Participar desde tus intereses"] },
  fr: { english: ["Dire qui vous êtes", "Décrire votre personnalité", "Gérer les besoins immédiats", "Partager vos intérêts"], french: ["Dire qui vous êtes", "Décrire votre personnalité", "Demander de l’aide clairement", "Transformer vos intérêts en conversation"], spanish: ["Dire qui vous êtes", "Créer des liens", "Gérer les besoins immédiats", "Participer à partir de vos intérêts"] },
  de: { english: ["Sagen, wer du bist", "Deine Persönlichkeit beschreiben", "Das Wichtigste jetzt bewältigen", "Deine Interessen teilen"], french: ["Sagen, wer du bist", "Deine Persönlichkeit beschreiben", "Klar um Hilfe bitten", "Interessen ins Gespräch bringen"], spanish: ["Sagen, wer du bist", "Beziehungen aufbauen", "Unmittelbare Bedürfnisse bewältigen", "Über deine Interessen teilnehmen"] },
  it: { english: ["Dire chi sei", "Descrivere la tua personalità", "Gestire ciò che conta ora", "Condividere i tuoi interessi"], french: ["Dire chi sei", "Descrivere la tua personalità", "Chiedere aiuto con chiarezza", "Trasformare gli interessi in conversazione"], spanish: ["Dire chi sei", "Costruire relazioni", "Gestire i bisogni immediati", "Partecipare attraverso i tuoi interessi"] },
  pt: { english: ["Dizer quem você é", "Descrever sua personalidade", "Lidar com o que importa agora", "Compartilhar seus interesses"], french: ["Dizer quem você é", "Descrever sua personalidade", "Pedir ajuda com clareza", "Transformar interesses em conversa"], spanish: ["Dizer quem você é", "Criar relações", "Lidar com necessidades imediatas", "Participar por meio dos seus interesses"] },
};

const hubCopy: WithEnglish<Record<string, string>> = {
  en: { baseEye: "Global Speaker · Foundation route", baseTitle: "Eight lessons that build a usable personal base.", baseIntro: "Move from identity to interaction through the four principles of the method.", built: "Built around you", builtTitle: "Learn what your life asks for.", builtIntro: "A useful language path follows situations before syllabi.", lifeEye: "Your life · six doors", lifeTitle: "Enter the curriculum from where you already are.", lifeIntro: "Explore the same lesson graph by level or by the part of life where language becomes useful.", connected: "connected lessons", explore: "Explore this life area", movement: "The learning movement", movementTitle: "From experience to interaction.", movementIntro: "Notice what is happening. Build the thought. Connect it to language. Say it. Use it with someone.", method: "See how the method works", curriculum: "Curriculum", path: "Continue beyond the foundation.", pathIntro: "Explore the wider curriculum by CEFR level and real-life environment.", lessons: "lessons", exploreLang: "Explore", idea: "Start with one useful idea.", resources: "All free resources", fromPolyglot: "From Polyglot", polyglotIntro: "How this language connects to others you might already speak or want to learn next.", next: "Organize your route", make: "Turn these lessons into your learning path.", cta: "Use your Language Map to prioritize the needs, situations, and interests that should come next." },
  es: { baseEye: "Global Speaker · Ruta base", baseTitle: "Ocho lecciones para construir una base personal y utilizable.", baseIntro: "Avanza desde la identidad hasta la interacción mediante los cuatro principios del método.", built: "Construido alrededor de ti", builtTitle: "Aprende lo que tu vida te pide.", builtIntro: "Una ruta útil sigue situaciones reales antes que temarios abstractos.", lifeEye: "Tu vida · seis puertas", lifeTitle: "Entra al currículo desde donde ya estás.", lifeIntro: "Explora el mismo recorrido por nivel o por la parte de tu vida donde el idioma se vuelve útil.", connected: "lecciones conectadas", explore: "Explorar esta área de vida", movement: "El movimiento de aprendizaje", movementTitle: "De la experiencia a la interacción.", movementIntro: "Observa lo que ocurre. Construye la idea. Conéctala con el idioma. Dila. Úsala con alguien.", method: "Ver cómo funciona el método", curriculum: "Currículo", path: "Continúa después de la ruta base.", pathIntro: "Explora el currículo amplio por nivel MCER y entorno de vida.", lessons: "lecciones", exploreLang: "Explorar", idea: "Empieza con una idea útil.", resources: "Todos los recursos gratuitos", fromPolyglot: "Desde Polyglot", polyglotIntro: "Cómo se conecta este idioma con otros que ya hablas o quieres aprender después.", next: "Organiza tu recorrido", make: "Convierte estas lecciones en tu ruta de aprendizaje.", cta: "Usa tu Mapa de Idioma para priorizar las necesidades, situaciones e intereses que deben continuar." },
  fr: { baseEye: "Global Speaker · Parcours de base", baseTitle: "Huit leçons pour construire une base personnelle et utilisable.", baseIntro: "Progressez de l’identité vers l’interaction à travers les quatre principes de la méthode.", built: "Construit autour de vous", builtTitle: "Apprenez ce que votre vie vous demande.", builtIntro: "Un parcours utile suit les situations avant les programmes abstraits.", lifeEye: "Votre vie · six portes", lifeTitle: "Entrez dans le programme depuis l’endroit où vous êtes déjà.", lifeIntro: "Explorez le même parcours par niveau ou par la partie de votre vie où la langue devient utile.", connected: "leçons associées", explore: "Explorer ce domaine de vie", movement: "Le mouvement d’apprentissage", movementTitle: "De l’expérience à l’interaction.", movementIntro: "Observez ce qui se passe. Construisez l’idée. Reliez-la à la langue. Dites-la. Utilisez-la avec quelqu’un.", method: "Voir comment fonctionne la méthode", curriculum: "Programme", path: "Continuez après le parcours de base.", pathIntro: "Explorez le programme élargi par niveau CECR et contexte de vie.", lessons: "leçons", exploreLang: "Explorer", idea: "Commencez avec une idée utile.", resources: "Toutes les ressources gratuites", fromPolyglot: "Depuis Polyglot", polyglotIntro: "Comment cette langue se connecte à d’autres que vous parlez peut-être déjà ou voulez apprendre ensuite.", next: "Organisez votre parcours", make: "Transformez ces leçons en parcours d’apprentissage.", cta: "Utilisez votre carte linguistique pour prioriser les besoins, situations et intérêts à développer ensuite." },
  de: { baseEye: "Global Speaker · Grundlagenroute", baseTitle: "Acht Lektionen, die eine praktische persönliche Grundlage schaffen.", baseIntro: "Bewege dich von Identität zu Interaktion durch die vier Prinzipien der Methode.", built: "Auf dich zugeschnitten", builtTitle: "Lerne, was dein Leben von dir verlangt.", builtIntro: "Ein nützlicher Sprachweg folgt Situationen, bevor er Lehrplänen folgt.", lifeEye: "Dein Leben · sechs Türen", lifeTitle: "Betritt den Lehrplan dort, wo du bereits bist.", lifeIntro: "Entdecke denselben Lernweg nach Niveau oder nach dem Lebensbereich, in dem Sprache für dich nützlich wird.", connected: "verbundene Lektionen", explore: "Diesen Lebensbereich erkunden", movement: "Der Lernweg", movementTitle: "Von der Erfahrung zur Interaktion.", movementIntro: "Nimm wahr, was passiert. Forme den Gedanken. Verbinde ihn mit Sprache. Sag es. Nutze es mit jemandem.", method: "So funktioniert die Methode", curriculum: "Lehrplan", path: "Geh über die Grundlagen hinaus.", pathIntro: "Entdecke den weiteren Lehrplan nach GER-Niveau und realem Lebensumfeld.", lessons: "Lektionen", exploreLang: "Entdecken", idea: "Beginne mit einer nützlichen Idee.", resources: "Alle kostenlosen Ressourcen", fromPolyglot: "Von Polyglot", polyglotIntro: "Wie diese Sprache mit anderen zusammenhängt, die du vielleicht schon sprichst oder als Nächstes lernen möchtest.", next: "Deinen Weg organisieren", make: "Mach aus diesen Lektionen deinen Lernweg.", cta: "Nutze deine Language Map, um die Bedürfnisse, Situationen und Interessen zu priorisieren, die als Nächstes wichtig für dich sind." },
  it: { baseEye: "Global Speaker · Percorso di base", baseTitle: "Otto lezioni per costruire una base personale che puoi usare davvero.", baseIntro: "Dall’identità all’interazione attraverso i quattro principi del metodo.", built: "Costruito intorno a te", builtTitle: "Impara ciò che la tua vita ti chiede.", builtIntro: "Un percorso linguistico utile parte dalle situazioni prima che dai programmi.", lifeEye: "La tua vita · sei porte", lifeTitle: "Entra nel percorso da dove sei già.", lifeIntro: "Esplora lo stesso insieme di lezioni per livello o per l’ambito della vita in cui la lingua diventa utile.", connected: "lezioni collegate", explore: "Esplora quest’area della vita", movement: "Il percorso di apprendimento", movementTitle: "Dall’esperienza all’interazione.", movementIntro: "Nota cosa sta succedendo. Costruisci il pensiero. Collegalo alla lingua. Dillo. Usalo con qualcuno.", method: "Scopri come funziona il metodo", curriculum: "Percorso didattico", path: "Vai oltre le basi.", pathIntro: "Esplora il percorso completo per livello QCER e contesto della vita reale.", lessons: "lezioni", exploreLang: "Esplora", idea: "Parti da un’idea utile.", resources: "Tutte le risorse gratuite", fromPolyglot: "Da Polyglot", polyglotIntro: "Come questa lingua si collega ad altre che magari già parli o vuoi imparare in seguito.", next: "Organizza il tuo percorso", make: "Trasforma queste lezioni nel tuo percorso di apprendimento.", cta: "Usa la tua Language Map per dare priorità ai bisogni, alle situazioni e agli interessi che dovrebbero venire dopo." },
  pt: { baseEye: "Global Speaker · Rota de base", baseTitle: "Oito lições para construir uma base pessoal que você realmente pode usar.", baseIntro: "Passe da identidade à interação pelos quatro princípios do método.", built: "Construído para você", builtTitle: "Aprenda o que a sua vida pede.", builtIntro: "Um caminho de aprendizagem útil acompanha as situações antes de seguir um programa.", lifeEye: "Sua vida · seis portas", lifeTitle: "Entre no currículo a partir de onde você já está.", lifeIntro: "Explore o mesmo conjunto de lições por nível ou pela área da vida em que o idioma se torna útil.", connected: "lições conectadas", explore: "Explorar esta área da vida", movement: "O movimento da aprendizagem", movementTitle: "Da experiência à interação.", movementIntro: "Perceba o que está acontecendo. Construa o pensamento. Conecte-o ao idioma. Diga. Use-o com alguém.", method: "Veja como o método funciona", curriculum: "Currículo", path: "Continue além da base.", pathIntro: "Explore o currículo completo por nível QECR e contexto da vida real.", lessons: "lições", exploreLang: "Explorar", idea: "Comece com uma ideia útil.", resources: "Todos os recursos gratuitos", fromPolyglot: "Do Polyglot", polyglotIntro: "Como este idioma se conecta a outros que você talvez já fale ou queira aprender a seguir.", next: "Organize sua rota", make: "Transforme estas lições no seu caminho de aprendizagem.", cta: "Use seu Language Map para priorizar as necessidades, situações e interesses que devem vir a seguir." },
};

function areaLabel(locale: InterfaceLocale, environment: string) {
  const copy = pickLocaleCopy(areaCopy, locale);
  return areaSlugs.includes(environment as AreaSlug) ? copy[environment as AreaSlug][0] : environment;
}

export function generateStaticParams() { return activeLanguages.map((language) => ({ language: language.key })); }

export async function generateMetadata({ params }: PageProps<"/learn/[language]">): Promise<Metadata> {
  const { language } = await params;
  const locale = await getInterfaceLocale();
  const profile = languages.find((item) => item.key === language && item.status === "active");
  if (!profile) return {};
  const hero = pickLocaleCopy(heroCopy, locale)[profile.key] ?? heroCopy.en[profile.key];
  return hero ? { title: hero.title, description: hero.copy, alternates: { canonical: `/learn/${profile.key}` } } : {};
}

export default async function LanguageHubPage({ params }: PageProps<"/learn/[language]">) {
  const { language } = await params;
  const locale = await getInterfaceLocale();
  const c = pickLocaleCopy(hubCopy, locale);
  const profile = languages.find((item) => item.key === language && item.status === "active");
  if (!profile) notFound();
  const hero = pickLocaleCopy(heroCopy, locale)[profile.key] ?? heroCopy.en[profile.key];
  if (!hero) notFound();
  const examples = pickLocaleCopy(hubExamples, locale)[profile.key] ?? hubExamples.en[profile.key];
  if (!examples) notFound();
  const curriculum = getCurriculumLessons(profile.key as CurriculumLanguage, locale);
  const curriculumByLevel = cefrOrder.map((level) => ({ level, lessons: curriculum.filter((lesson) => lesson.level === level) })).filter((group) => group.lessons.length);
  const foundation = getLocalizedFoundationLessonIds(locale, profile.key).flatMap((lessonId) => {
    const lesson = getCurriculumLessonById(lessonId, locale);
    const override = getLocalizedCurriculumOverride(locale, lessonId);
    return lesson && override ? [{ lesson, pillar: override.pillar, sequence: override.sequence }] : [];
  });
  const polyglotArticles = getPolyglotArticlesForLanguage(profile.key);
  const related = resources.filter((resource) => resource.language === profile.key).slice(0, 3);
  const areas = areaSlugs.map((slug) => ({ slug, title: pickLocaleCopy(areaCopy, locale)[slug][0], note: pickLocaleCopy(areaCopy, locale)[slug][1], count: curriculum.filter((lesson) => lesson.primaryEnvironment === slug || lesson.secondaryEnvironments.includes(slug)).length }));

  return <>
    <PageIntro eyebrow={hero.eyebrow} title={hero.title} copy={hero.copy} accent={profile.accent} note={profile.nativeName} />
    {foundation.length ? <section className="section"><div className="container"><SectionHeading eyebrow={c.baseEye} title={c.baseTitle} intro={c.baseIntro} /><div className="resource-grid mt-10">{foundation.map(({ lesson, pillar, sequence }) => <Link className="resource-card" key={lesson.id} href={`/learn/${lesson.language}/${lesson.slug}`}><p className="eyebrow">{String(sequence).padStart(2, "0")} · {pillar}</p><h3>{lesson.title}</h3><p>{lesson.learningObjective}</p><span className="resource-card__link">{c.explore} <i aria-hidden="true">→</i></span></Link>)}</div></div></section> : null}
    <section className="section hub-pillars"><div className="container"><SectionHeading eyebrow={c.built} title={c.builtTitle} intro={c.builtIntro} /><div className="hub-pillar-grid">{examples.map((item, index) => <article key={item}><span>0{index + 1}</span><h3>{item}</h3></article>)}</div></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow={c.lifeEye} title={c.lifeTitle} intro={c.lifeIntro} /><div className="resource-grid mt-10">{areas.map((area) => <Link className="resource-card" key={area.slug} href={`/learn/${profile.key}/life/${area.slug}`}><p className="eyebrow">{area.count} {c.connected}</p><h3>{area.title}</h3><p>{area.note}</p><span className="resource-card__link">{c.explore} <i aria-hidden="true">→</i></span></Link>)}</div></div></section>
    <section className={`section hub-method hub-method--${profile.accent}`}><div className="container"><SectionHeading eyebrow={c.movement} title={c.movementTitle} intro={c.movementIntro} /><MethodSequence compact /><ButtonLink href="/method" variant="secondary">{c.method}</ButtonLink></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow={`${c.curriculum} · ${curriculum.length} ${c.lessons}`} title={c.path} intro={c.pathIntro} /><div className="mt-12 space-y-4">{curriculumByLevel.map((group, index) => <details key={group.level} open={index === 0} className="border-t border-[var(--line)] py-5"><summary className="flex cursor-pointer list-none items-baseline justify-between gap-6 py-2"><span className="font-[var(--serif)] text-3xl">{group.level}</span><span className="text-xs font-bold uppercase tracking-[.12em] text-[var(--ink-soft)]">{group.lessons.length} {c.lessons}</span></summary><div className="resource-grid mt-6">{group.lessons.map((lesson) => <Link className="resource-card" key={lesson.id} href={`/learn/${lesson.language}/${lesson.slug}`}><p className="eyebrow">{lesson.level} · {areaLabel(locale, lesson.primaryEnvironment)}</p><h3>{lesson.title}</h3><p>{lesson.learningObjective}</p></Link>)}</div></details>)}</div></div></section>
    {polyglotArticles.length ? <section className="section"><div className="container"><SectionHeading eyebrow={c.fromPolyglot} title={`${c.fromPolyglot} · ${profile.nativeName}`} intro={c.polyglotIntro} /><div className="resource-grid resource-grid--preview">{polyglotArticles.map((article) => <Link className="resource-card" key={article.slug} href={`/polyglot/${article.slug}`}><p className="eyebrow">{polyglotTopics.find((topic) => topic.key === article.topic)?.label ?? article.topic} · {article.readingMinutes} min</p><h3>{article.title}</h3><p>{article.description}</p></Link>)}</div></div></section> : null}
    <section className="section"><div className="container"><div className="resources-preview__heading"><SectionHeading eyebrow={`${c.exploreLang} ${profile.nativeName}`} title={c.idea} /><ButtonLink href="/resources" variant="text">{c.resources}</ButtonLink></div><div className="resource-grid resource-grid--preview">{related.map((resource, index) => <ResourceCard key={resource.slug} resource={resource} index={index} />)}</div></div></section>
    <CTASection eyebrow={`${profile.code} · ${c.next}`} title={c.make} copy={c.cta} />
  </>;
}
